x-veld:
  chain:
    description: "publish SpaCy text classification models trained during the MARA project to
      huggingface"
    topics:
      - "NLP"

services:
  veld:
    # overwrite the veld_code's dockerfile with this parameter
    build: .
    extends:
      file: ./veld_code_11_publish_to_hf/veld.yaml
      service: veld
    volumes:
      - ./veld_data_19_mara_models/data/:/veld/input/
    environment:
      in_model_folder: "mo3"
      version: 0.1
      model_name: "mo3"

